[workspace]
members = [
    "aes-ctr",
    "cfb8",
    "cfb-mode",
    "chacha20",
    "ctr",
    "hc-256",
    "ofb",
    "salsa20",
]

[patch.crates-io]
block-cipher = { git = "https://github.com/RustCrypto/traits" }
